apiVersion: v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skillupnodejs
  template:
    metadata:
      labels:
        app: skillupnodejs
    spec:
      containers:
      - name: skillupnodejs
        image: adityasinghajeri/skillup_project:latest  # <-- Replace with your image
        ports:
        - containerPort: 9595