apiVersion: v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skillupnodejs
  template:
    metadata:
      labels:
        app: skillupnodejs
    spec:
      containers:
      - name: skillupnodejs
        image: adityasinghajeri/skillup_project:latest  # <-- Replace with your image
        ports:
        - containerPort: 9595
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: skillupnodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9595
  type: LoadBalancer
